"""CliRunner smoke tests for the Typer scaffold (epic #959, Wave 0 — issue #1120).

These tests stand up the ``typer.testing.CliRunner`` infrastructure *before* the
first command is migrated, so Waves 1–4 can be written test-first. They cover the
scaffold contract only:

* ``--version`` prints ``src.__version__`` and exits (parity with argparse).
* ``--help`` / no-args show usage without running startup side effects.
* ``--config`` exports ``TG_CONFIG_PATH`` as an abspath (the one side effect the
  whole migration depends on).
* ``run_async`` is the single async bridge.

The scaffold has no leaf commands yet (Wave 0 is pure infrastructure), so the
``--config`` side effect — which Typer only runs when a subcommand is invoked —
is exercised via a throwaway ``probe`` command registered on a *fresh* Typer app
that reuses ``main_callback``. This never touches the production ``app``, so the
invariant "no command name appears or disappears" holds.
"""

from __future__ import annotations

import asyncio
import os
from unittest.mock import patch

import pytest
import typer
from typer.testing import CliRunner

from src import __version__
from src.cli import typer_app
from src.cli.typer_app import DEFAULT_CONFIG, app, main_callback, run_async

runner = CliRunner()


def _app_with_probe() -> typer.Typer:
    """Build a throwaway Typer app reusing the real callback + a no-op command.

    Typer only invokes ``@app.callback()`` when a subcommand runs, and the
    production ``app`` has no commands yet (Wave 0). To exercise the callback's
    side effects we register a minimal ``probe`` command on a fresh app that
    binds the *same* ``main_callback``. The production ``app`` stays untouched.
    """
    probe_app = typer.Typer(no_args_is_help=True)
    probe_app.callback()(main_callback)

    @probe_app.command("probe")
    def _probe() -> None:
        typer.echo("PROBE_OK")

    return probe_app


# --------------------------------------------------------------------------- #
# Global options: --version / --help / no-args
# --------------------------------------------------------------------------- #


class TestGlobalOptions:
    def test_version_flag_prints_version_and_exits(self):
        """--version prints ``src.__version__`` and exits 0 (argparse parity)."""
        result = runner.invoke(app, ["--version"])
        assert result.exit_code == 0
        # The version string itself must match the argparse path exactly; this is
        # the hard invariant from #1120 (``--version`` via ``src.__version__``).
        assert __version__ in result.output
        assert result.output.strip() == f"src {__version__}"

    def test_version_flag_skips_startup_side_effects(self):
        """--version is eager: logging/data-dirs/dotenv never run for it."""
        with (
            patch.object(typer_app, "setup_logging") as mock_log,
            patch.object(typer_app, "ensure_data_dirs") as mock_dirs,
            patch.object(typer_app, "load_cli_dotenv") as mock_dotenv,
        ):
            result = runner.invoke(app, ["--version"])
        assert result.exit_code == 0
        mock_log.assert_not_called()
        mock_dirs.assert_not_called()
        mock_dotenv.assert_not_called()

    def test_help_flag_shows_usage(self):
        """--help shows the app help (auto-generated by Typer)."""
        result = runner.invoke(app, ["--help"])
        assert result.exit_code == 0
        assert "TG Post Search" in result.output
        # Global options must be advertised in help.
        assert "--config" in result.output
        assert "--version" in result.output

    def test_help_flag_skips_startup_side_effects(self):
        """--help uses resilient parsing: no startup side effects fire."""
        with (
            patch.object(typer_app, "setup_logging") as mock_log,
            patch.object(typer_app, "ensure_data_dirs") as mock_dirs,
            patch.object(typer_app, "load_cli_dotenv") as mock_dotenv,
        ):
            result = runner.invoke(app, ["--help"])
        assert result.exit_code == 0
        mock_log.assert_not_called()
        mock_dirs.assert_not_called()
        mock_dotenv.assert_not_called()

    def test_no_args_shows_help(self):
        """no_args_is_help=True → bare invocation shows help (non-zero exit)."""
        result = runner.invoke(app, [])
        # Typer exits 2 for the no-args-is-help path; the key contract is that it
        # does not crash and surfaces usage.
        assert result.exit_code == 2
        assert "Usage" in result.output or "Commands" in result.output


# --------------------------------------------------------------------------- #
# --config side effect: TG_CONFIG_PATH export (the migration's load-bearing bit)
# --------------------------------------------------------------------------- #


class TestConfigSideEffect:
    def test_config_exports_abspath_to_environ(self, monkeypatch):
        """--config <path> exports TG_CONFIG_PATH as an absolute path."""
        monkeypatch.delenv("TG_CONFIG_PATH", raising=False)
        # Keep the test hermetic: stub the FS/logging side effects so only the
        # TG_CONFIG_PATH export is under test.
        with (
            patch.object(typer_app, "setup_logging"),
            patch.object(typer_app, "ensure_data_dirs"),
            patch.object(typer_app, "load_cli_dotenv"),
        ):
            result = runner.invoke(_app_with_probe(), ["--config", "myconf.yaml", "probe"])

        assert result.exit_code == 0
        assert result.output.strip() == "PROBE_OK"
        exported = os.environ["TG_CONFIG_PATH"]
        assert os.path.isabs(exported)
        assert exported == os.path.abspath("myconf.yaml")
        assert exported.endswith("myconf.yaml")

    def test_default_config_is_config_yaml(self, monkeypatch):
        """Without --config the default mirrors argparse (config.yaml)."""
        assert DEFAULT_CONFIG == "config.yaml"
        monkeypatch.delenv("TG_CONFIG_PATH", raising=False)
        with (
            patch.object(typer_app, "setup_logging"),
            patch.object(typer_app, "ensure_data_dirs"),
            patch.object(typer_app, "load_cli_dotenv"),
        ):
            result = runner.invoke(_app_with_probe(), ["probe"])

        assert result.exit_code == 0
        exported = os.environ["TG_CONFIG_PATH"]
        assert exported == os.path.abspath("config.yaml")

    def test_config_runs_startup_side_effects_in_order(self, monkeypatch):
        """A real subcommand triggers dotenv + logging + data-dirs (1:1 main())."""
        monkeypatch.delenv("TG_CONFIG_PATH", raising=False)
        with (
            patch.object(typer_app, "setup_logging") as mock_log,
            patch.object(typer_app, "ensure_data_dirs") as mock_dirs,
            patch.object(typer_app, "load_cli_dotenv") as mock_dotenv,
        ):
            result = runner.invoke(_app_with_probe(), ["--config", "x.yaml", "probe"])

        assert result.exit_code == 0
        # Same trio of side effects as src/cli/main.py::main(), and dotenv is
        # passed the raw config path (not the abspath), matching main().
        mock_dotenv.assert_called_once_with("x.yaml")
        mock_log.assert_called_once_with()
        mock_dirs.assert_called_once_with()


# --------------------------------------------------------------------------- #
# Async bridge: run_async
# --------------------------------------------------------------------------- #


class TestRunAsync:
    def test_run_async_returns_coroutine_result(self):
        """run_async drives a coroutine to completion and returns its value."""

        async def _impl(x: int) -> int:
            return x * 2

        assert run_async(_impl(21)) == 42

    def test_run_async_propagates_exceptions(self):
        """Exceptions raised inside the coroutine surface to the caller."""

        async def _boom() -> None:
            raise ValueError("kaboom")

        with pytest.raises(ValueError, match="kaboom"):
            run_async(_boom())

    def test_run_async_uses_asyncio_run(self):
        """The bridge funnels through exactly one asyncio.run (no nested loops)."""

        async def _impl() -> str:
            return "ok"

        with patch.object(typer_app.asyncio, "run", wraps=asyncio.run) as mock_run:
            assert run_async(_impl()) == "ok"
        mock_run.assert_called_once()

    def test_command_pattern_def_delegates_to_run_async(self):
        """The documented pattern: a plain ``def`` command calls run_async(_impl)."""
        seen: list[int] = []

        async def _impl(value: int) -> None:
            seen.append(value)

        # A migrated command stays synchronous (Typer reads its type-hints) and
        # delegates the async body through run_async — this is the contract
        # Waves 1–4 follow.
        def command(value: int = 7) -> None:
            run_async(_impl(value))

        command()
        assert seen == [7]
