from __future__ import annotations

CLI_REAL_TG_COMMAND_CASES_BY_CATEGORY: dict[str, set[tuple[str, ...]]] = {
    "safe_ro": {
        ("account", "flood-status"),
        ("account", "info"),
        ("account", "list"),
        ("agent", "messages"),
        ("agent", "threads"),
        ("analytics", "calendar"),
        ("analytics", "channel"),
        ("analytics", "content-types"),
        ("analytics", "daily"),
        ("analytics", "hourly"),
        ("analytics", "peak-hours"),
        ("analytics", "pipeline-stats"),
        ("analytics", "summary"),
        ("analytics", "top"),
        ("analytics", "trending-channels"),
        ("analytics", "trending-emojis"),
        ("analytics", "trending-topics"),
        ("analytics", "velocity"),
        ("channel", "list"),
        ("channel", "stats"),
        ("channel", "tag", "get"),
        ("channel", "tag", "list"),
        ("collect", "sample"),
        ("debug", "logs"),
        ("debug", "memory"),
        ("debug", "timing"),
        ("dialogs", "broadcast-stats"),
        ("dialogs", "cache-status"),
        ("dialogs", "list"),
        ("dialogs", "participants"),
        ("dialogs", "resolve"),
        ("dialogs", "topics"),
        ("export", "csv"),
        ("export", "json"),
        ("export", "rss"),
        ("filter", "analyze"),
        ("filter", "precheck"),
        ("image", "generated"),
        ("image", "providers"),
        ("messages", "read"),
        ("notification", "dry-run"),
        ("notification", "status"),
        ("photo-loader", "dialogs"),
        ("pipeline", "dry-run-count"),
        ("pipeline", "filter", "show"),
        ("pipeline", "graph"),
        ("pipeline", "list"),
        ("pipeline", "moderation-list"),
        ("pipeline", "moderation-view"),
        ("pipeline", "queue"),
        ("pipeline", "run-show"),
        ("pipeline", "runs"),
        ("pipeline", "show"),
        ("pipeline", "templates"),
        ("provider", "list"),
        ("scheduler", "status"),
        ("search",),
        ("search-query", "get"),
        ("search-query", "list"),
        ("search-query", "stats"),
        ("settings", "get"),
        ("settings", "info"),
        ("settings", "server-time"),
        ("test", "read"),
        ("translate", "stats"),
    },
    "safe_write": {
        ("agent", "chat"),
        ("agent", "threads"),
        ("channel", "add"),
        ("channel", "add-bulk"),
        ("dialogs", "download-media"),
        ("photo-loader", "refresh"),
        ("pipeline", "export"),
    },
    "mutating": {
        ("channel", "refresh-meta"),
        ("scheduler", "start"),
        ("scheduler", "trigger"),
    },
    "mutation_safe": {
        ("dialogs", "archive"),
        ("dialogs", "edit-message"),
        ("dialogs", "mark-read"),
        ("dialogs", "pin-message"),
        ("dialogs", "react"),
        ("dialogs", "send"),
        ("dialogs", "unarchive"),
        ("dialogs", "unpin-message"),
        ("my-telegram", "archive"),
        ("my-telegram", "edit-message"),
        ("my-telegram", "mark-read"),
        ("my-telegram", "pin-message"),
        ("my-telegram", "react"),
        ("my-telegram", "send"),
        ("my-telegram", "unarchive"),
        ("my-telegram", "unpin-message"),
    },
    "destructive": {
        ("restart",),
        ("serve",),
        ("stop",),
        ("worker",),
    },
    "manual": {
        ("dialogs", "create-channel"),
        ("dialogs", "delete-message"),
        ("dialogs", "send"),
    },
    "heavy": {
        ("channel", "collect"),
        ("channel", "refresh-meta", "--all"),
        ("channel", "refresh-types"),
        ("channel", "stats", "--all"),
        ("collect",),
        ("dialogs", "refresh"),
        ("test", "all"),
        ("test", "benchmark"),
        ("test", "telegram"),
    },
}

CLI_REAL_TG_CLEANUP_COMMAND_CASES: set[tuple[str, ...]] = {
    ("agent", "thread-delete"),
    ("agent", "threads"),
    ("dialogs", "archive"),
    ("dialogs", "edit-message"),
    ("dialogs", "leave"),
    ("dialogs", "pin-message"),
    ("dialogs", "react"),
    ("dialogs", "unarchive"),
    ("dialogs", "unpin-message"),
    ("my-telegram", "archive"),
    ("my-telegram", "edit-message"),
    ("my-telegram", "pin-message"),
    ("my-telegram", "react"),
    ("my-telegram", "unarchive"),
    ("my-telegram", "unpin-message"),
    ("scheduler", "clear-pending"),
}

CLI_REAL_TG_MANUAL_OR_EXCLUDED_COMMANDS: dict[tuple[str, ...], str] = {
    ("account", "add"): "manual account onboarding/session import",
    ("account", "delete"): "local account destructive write",
    ("account", "flood-clear"): "local flood state mutation",
    ("account", "send-code"): "Telegram auth flow",
    ("account", "toggle"): "local account state mutation",
    ("account", "verify-code"): "Telegram auth flow",
    ("agent", "context"): "local agent-thread mutation requiring chosen target",
    ("agent", "test-escaping"): "diagnostic aggregate, not a leaf operator smoke",
    ("agent", "test-tools"): "diagnostic aggregate, not a leaf operator smoke",
    ("agent", "thread-create"): "local agent-thread mutation",
    ("agent", "thread-delete"): "cleanup-only live CLI command; deletes agent thread rows",
    ("agent", "thread-rename"): "local agent-thread mutation",
    ("agent", "thread-stop"): "local agent-stream cancel + last-exchange rollback (DB-only)",
    ("channel", "delete"): "local channel destructive write",
    ("channel", "import"): "bulk local channel write",
    ("channel", "list-for-import"): "list-only but depends on mutable dialog cache / live dialogs",
    ("channel", "tag", "add"): "local tag write",
    ("channel", "tag", "delete"): "local tag destructive write",
    ("channel", "tag", "set"): "local channel tag write",
    ("channel", "toggle"): "local channel state mutation",
    ("dialogs", "cache-clear"): "local dialog cache mutation",
    ("dialogs", "edit-admin"): "Telegram-visible admin mutation",
    ("dialogs", "edit-permissions"): "Telegram-visible permissions mutation",
    ("dialogs", "forward"): "Telegram-visible message forward",
    ("dialogs", "join"): "Telegram-visible join/subscribe action",
    ("dialogs", "kick"): "Telegram-visible participant mutation",
    ("dialogs", "leave"): "cleanup-only live CLI command; leaves/deletes a channel created during the test",
    ("dialogs", "queue", "cancel"): "local telegram_commands queue cancel — DB-only mutation",
    ("dialogs", "queue", "clear-pending"): "local telegram_commands queue cancel — DB-only mutation",
    ("dialogs", "queue", "status"): "list-only but depends on mutable telegram_commands queue",
    ("filter", "apply"): "local filter mutation",
    ("filter", "hard-delete"): "local destructive delete",
    ("filter", "purge"): "local message deletion",
    ("filter", "purge-messages"): "local message deletion",
    ("filter", "reset"): "local filter mutation",
    ("filter", "toggle"): "local filter mutation",
    ("image", "generate"): "provider spend/write operation",
    ("image", "models"): "provider/network enumeration",
    ("my-telegram", "broadcast-stats"): "alias of dialogs broadcast-stats",
    ("my-telegram", "cache-clear"): "alias of dialogs cache-clear",
    ("my-telegram", "cache-status"): "alias of dialogs cache-status",
    ("my-telegram", "create-channel"): "alias of dialogs create-channel",
    ("my-telegram", "delete-message"): "alias of dialogs delete-message",
    ("my-telegram", "download-media"): "alias of dialogs download-media",
    ("my-telegram", "edit-admin"): "alias of dialogs edit-admin",
    ("my-telegram", "edit-permissions"): "alias of dialogs edit-permissions",
    ("my-telegram", "forward"): "alias of dialogs forward",
    ("my-telegram", "join"): "alias of dialogs join",
    ("my-telegram", "kick"): "alias of dialogs kick",
    ("my-telegram", "leave"): "alias of dialogs leave",
    ("my-telegram", "list"): "alias of dialogs list",
    ("my-telegram", "participants"): "alias of dialogs participants",
    ("my-telegram", "queue", "cancel"): "alias of dialogs queue cancel",
    ("my-telegram", "queue", "clear-pending"): "alias of dialogs queue clear-pending",
    ("my-telegram", "queue", "status"): "alias of dialogs queue status",
    ("my-telegram", "refresh"): "alias of dialogs refresh",
    ("my-telegram", "resolve"): "alias of dialogs resolve",
    ("my-telegram", "topics"): "alias of dialogs topics",
    ("notification", "delete"): "BotFather/stateful notification mutation",
    ("notification", "set-account"): "local notification setting mutation",
    ("notification", "setup"): "BotFather/stateful notification mutation",
    ("notification", "test"): "Telegram-visible notification send",
    ("photo-loader", "auto-create"): "local auto-upload write",
    ("photo-loader", "auto-delete"): "local auto-upload destructive write",
    ("photo-loader", "auto-list"): "list-only but depends on mutable photo-loader setup",
    ("photo-loader", "auto-toggle"): "local auto-upload mutation",
    ("photo-loader", "auto-update"): "local auto-upload mutation",
    ("photo-loader", "batch-cancel"): "local photo batch mutation",
    ("photo-loader", "batch-create"): "local photo batch write",
    ("photo-loader", "batch-list"): "list-only but depends on mutable photo-loader setup",
    ("photo-loader", "items"): "list-only but depends on mutable photo-loader setup",
    ("photo-loader", "run-due"): "Telegram-visible photo send",
    ("photo-loader", "schedule-send"): "local scheduled send write",
    ("photo-loader", "send"): "Telegram-visible photo send",
    ("pipeline", "add"): "local pipeline write",
    ("pipeline", "ai-edit"): "provider spend/write operation",
    ("pipeline", "approve"): "local moderation mutation",
    ("pipeline", "bulk-approve"): "local moderation mutation",
    ("pipeline", "bulk-reject"): "local moderation mutation",
    ("pipeline", "delete"): "local pipeline destructive write",
    ("pipeline", "edge", "add"): "local pipeline graph write",
    ("pipeline", "edge", "remove"): "local pipeline graph write",
    ("pipeline", "edit"): "local pipeline write",
    ("pipeline", "filter", "clear"): "local pipeline filter write",
    ("pipeline", "filter", "set"): "local pipeline filter write",
    ("pipeline", "from-template"): "local pipeline write",
    ("pipeline", "generate"): "provider spend/write operation",
    ("pipeline", "generate-stream"): "provider spend/write operation",
    ("pipeline", "import"): "local pipeline write",
    ("pipeline", "node", "add"): "local pipeline graph write",
    ("pipeline", "node", "remove"): "local pipeline graph write",
    ("pipeline", "node", "replace"): "local pipeline graph write",
    ("pipeline", "publish"): "Telegram-visible publish",
    ("pipeline", "refinement-steps"): "local pipeline write",
    ("pipeline", "reject"): "local moderation mutation",
    ("pipeline", "run"): "provider spend/write operation",
    ("pipeline", "toggle"): "local pipeline state mutation",
    ("provider", "add"): "local provider secret/config write",
    ("provider", "delete"): "local provider config delete",
    ("provider", "probe"): "external provider network call",
    ("provider", "refresh"): "external provider network call and local write",
    ("provider", "test-all"): "external provider network calls",
    ("scheduler", "clear-pending"): "unsafe standalone live smoke; deletes all pending channel collection tasks",
    ("scheduler", "job-toggle"): "local scheduler setting mutation",
    ("scheduler", "queue-pause"): "local scheduler setting mutation",
    ("scheduler", "queue-resume"): "local scheduler setting mutation",
    ("scheduler", "set-interval"): "local scheduler setting mutation",
    ("scheduler", "stop"): "local scheduler setting mutation",
    ("scheduler", "task-cancel"): "local task mutation",
    ("search-query", "add"): "local search query write",
    ("search-query", "delete"): "local search query delete",
    ("search-query", "edit"): "local search query write",
    ("search-query", "run"): "live/provider-backed search execution",
    ("search-query", "toggle"): "local search query mutation",
    ("settings", "agent"): "local settings write",
    ("settings", "filter-criteria"): "local settings write",
    ("settings", "reactions"): "local settings write",
    ("settings", "semantic"): "local settings write",
    ("settings", "set"): "local settings write",
    ("test", "write"): "diagnostic aggregate with local DB writes",
    ("translate", "detect"): "local message backfill mutation",
    ("translate", "message"): "provider/network translation",
    ("translate", "run"): "provider/network translation and local write",
}
